stages:
  - unittests
  - build

tests:
  stage: unittests
  script:
    - apk update
    - apk add python3 postgresql-libs
    - apk add --update --no-cache --virtual .build-deps alpine-sdk python3-dev musl-dev postgresql-dev libffi-dev
    - pip3 install -U setuptools pip
    - pip3 install --no-cache-dir -r requirements.txt
    - python3 -m unittest discover tests *_test.py

pypi_build:
  stage: build
  script:
    - apk update
    - apk add python3 postgresql-libs
    - apk add --update --no-cache --virtual .build-deps alpine-sdk python3-dev musl-dev postgresql-dev libffi-dev
    - pip3 install -U setuptools pip
    - python setup.py sdist
    - pip3 install twine
    - twine upload dist/*